import "../styles/globals.css";
import "tailwindcss/tailwind.css";
import Default from "../layouts/Default";
import Head from "next/head";
import Sidebar from "../layouts/Sidebar";
function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Apotek</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="containerDefault flex">
        <Sidebar />
        <Component {...pageProps} />
      </div>
    </div>
  );
}

export default MyApp;
