import "../styles/globals.css";
import "tailwindcss/tailwind.css";
import Topbar from "../layouts/Topbar";
import Head from "next/head";
import Sidebar from "../layouts/Sidebar";
import { Provider } from "react-redux";
import { createWrapper } from "next-redux-wrapper";
import store from "../redux/store";
function MyApp({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <div>
        <Head>
          <title>Apotek</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="containerDefault flex">
          <Sidebar />
          <div className="w-full">
            <Topbar />
            <Component {...pageProps} />
          </div>
        </div>
      </div>
    </Provider>
  );
}
MyApp.getInitialProps = async ({ Component, ctx }) => {
  const pageProps = Component.getInitialProps
    ? await Component.getInitialProps(ctx)
    : {};

  //Anything returned here can be access by the client
  return { pageProps: pageProps };
};
const makeStore = () => store;
const wrapper = createWrapper(makeStore);
export default wrapper.withRedux(MyApp);
